/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("ábaco",
            "abajur",
            "açucareiro",
            "agogô",
            "agulha",
            "alaúde",
            "alfinete",
            "alforje",
            "algema",
            "alicate",
            "almofada",
            "almofariz",
            "ampulheta",
            "âncora",
            "bacia",
            "balaio",
            "balança",
            "balde",
            "bambolê",
            "banco",
            "bandeira",
            "bandolim",
            "batuta",
            "bazuca",
            "bengala",
            "berço",
            "berimbau",
            "bicicleta",
            "bidê",
            "bigorna",
            "binóculo",
            "biombo",
            "biruta",
            "cabide",
            "cadeado",
            "cadeira",
            "caderno",
            "cajado",
            "calculadora",
            "cálice",
            "campainha",
            "candeeiro",
            "candelabro",
            "caneca",
            "caneta",
            "canivete",
            "capa",
            "capacete",
            "cassete",
            "cassetete",
            "dado",
            "dardo",
            "dedal",
            "delineador",
            "dentadura",
            "descascador",
            "dicionário",
            "didjeridu",
            "dinamite",
            "discman",
            "disco",
            "esfregão",
            "esmalte",
            "garrafa",
            "gaveta",
            "geladeira",
            "grua",
            "guarda-chuva",
            "guardanapo",
            "guarda-sol",
            "hélice",
            "helicóptero",
            "helioscópio",
            "helióstato",
            "jato",
            "jaula",
            "jazigo",
            "jeans",
            "luneta",
            "manivela",
            "maquete",
            "máquina",
            "marimba",
            "marreta",
            "martelo",
            "máscara",
            "medalha",
            "megafone",
            "meia",
            "miçanga",
            "microfone",
            "microscópio",
            "míssil",
            "mochila",
            "panela",
            "pano",
            "papel",
            "parafuso",
            "paraquedas",
            "pedal",
            "pêndulo",
            "peruca",
            "peteca",
            "pote",
            "prancha",
            "prateleira",
            "prato",
            "quebra-cabeça",
            "queijeira",
            "quena",
            "quepe",
            "rédea",
            "régua",
            "relógio",
            "remo",
            "repelente",
            "retrovisor",
            "revista",
            "revólver",
            "rifle",
            "rímel",
            "sofá",
            "sombrinha",
            "trompete",
            "tuba",
            "violino",
            "xale",
            "yagi",
            "zambê",
            "zarabatana",
            "zinco")